### ISSUE TITLE
how to show only the first 6 images in ALL label? 

### ISSUE THREAD

**Issue by AntonioS30** [awplige/Portfolio-Filter-Gallery#1]
how to show only the first 6 images in ALL label?

**Comment by awplige** [comment]
This is not possible because of this plugin based on Jquery and All will take all the images which are in the other filters.

You can do it with the load more function that is available in the premium version.

See the demo - https://awplife.com/demo/portfolio-filter-gallery-premium/ajax-load-more/

Thanks
